version: '3.9'

services:
  web:
    image: dalfenchana/myimage:latest
    ports: 
      - 80:5000
    environment:
      - store_id_list=305
      - api_key=4c281f5053fde83d09ea4501a0dcd1ff387b9a3b
      - MONGO_INITDB_DATABASE=super_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - DB_URL=mongodb_host
    volumes:
      - ./:/apps
    links:
      - mongodb

  mongodb:
    image: mongo:latest
    hostname: mongodb_host
    ports:
      - 27017:27017
    volumes:
      - ./apps/mongo:/data/db
    environment:
      - MONGO_INITDB_DATABASE=super_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
